aws:
  endpoint: ${AWS_ENDPOINT:http://localhost:4566}
  region: ${AWS_REGION:us-east-1}
  sqs:
    queue-name: ticket-sales-queue
  dynamodb:
    table-name: payments

spring:
  application:
    name: ticket-sales-processor
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ticket-sales-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topics:
    payment-request: payment-request
    payment-response: payment-response

ratelimit:
  tps: 50
  concurrency: 50

otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4318}
  service:
    name: ticket-sales-processor
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: otlp
